language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=MW_OSD/
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DMINIMOSD"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DMICROMINIMOSD"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DAEROMAX"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DRTFQV1"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DRTFQMICRO"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DRUSHDUINO"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DKYLIN250PDB"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DAIRBOTMICRO"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DANDROMEDA"'

    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DBETAFLIGHT"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DBETAFLIGHT3"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DAPM"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DPIXHAWK"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DPIXHAWK"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DMULTIWII"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DMAHOWII"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DKISS"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DNAZA"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DLIBREPILOT"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DTAULABS"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DFIXEDWING_BF"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DFIXEDWING_BF_SERVO"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DHARAKIRI"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DRACEFLIGHT"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DSKYTRACK"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DGPSOSD_UBLOX"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DGPSOSD_NMEA"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DNOCONTROLLER"'

    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DMULTIWII_V23"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DMULTIWII_V21"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DBASEFLIGHT20150327"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DCLEANFLIGHT172"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DCLEANFLIGHT180"'
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DBETAFLIGHT2"'

install:
    - pip install -U platformio

script:
    - platformio ci --board=pro16MHzatmega328
 
