language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=MW_OSD/
    - PLATFORMIO_CI_SRC=MW_OSD/ PLATFORMIO_BUILD_FLAGS="-DMINIMOSD"'

install:
    - pip install -U platformio

script:
- platformio run -e pro16MHzatmega328_deploy
- cp .pioenvs/pro16MHzatmega328_deploy/firmware.hex .pioenvs/pro16MHzatmega328_deploy/minim.hex
- platformio run -e pro16MHzatmega328_deploy
- cp .pioenvs/pro16MHzatmega328_deploy/firmware.hex .pioenvs/pro16MHzatmega328_deploy/aeromax.hex

deploy:
  provider: releases
  skip_cleanup: false
  overwrite: true
  api_key:
    secure: y839CmJ4qqwaDupyjtqRwJOpJ/eB0QpSvo4Mkqyw2pyeIjlyC3509ddyFLHgUNViusIZYHN/KPpljXj4Hh71EDTvZ0qhI/plpBcspTgYV3vAOZ5l1JGjMSe730l7L1XQHMYKFk+pm++ulXMLXDqCuFOUo6nFPt2/Xli1hsYDq5tTZhGKBtUUEnV9kA95+pgAIK9LjNYFwynYLWFlXgvBN5zGVUqa+fQg4l1cQ4yJoHdcn5mFISSWla7zIG3rAQLyeidrvTQv7XuQrgI+fNqGIaTLh1OPmc1YB33myGJmxaJK+XshQfBiLISgvXpC6CXTYUQWytSZXB1cnxCX3spg4fiCsjZZ6SKCFox0zu4z084XNmajgxyqGr61QmTZTLB1iI3GZ7bhx+R18jro4GBzWSnMgZxipghF0xXnumaumg7LmWbcwWAlNNkSZVhrcI6NAIIWmjIJrzAgGGK5a1VbS0fvqt4GDmJcZYahaYdMzekW9jTaMdZE4AzQ3tYJJus2GMoCWJ3K16SMBf9ZmR+ILScQXkP5CoApym6+ZmROrHZViRsihQdC7EiRiKy6XrivUmVUXCZLxIO+OU9gRpG41RQbl9whgr+sd4UXWCZsV9mzJ5c1CiNnnvJmfjhcEIHw6JATdaMdlm6M680QPi3Vvcx5xJcjZ8cUQCoqemoNuQc=
  file: ".pioenvs/pro16MHzatmega328_deploy/firmware.hex"
  file: ".pioenvs/pro16MHzatmega328_deploy/minim.hex"
    
branches:
  only:
  - TRAVIS
