language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=MW_OSD/MW_OSD.ino
    - PLATFORMIO_CI_SRC=MW_OSD/GPS.ino
    - PLATFORMIO_CI_SRC=MW_OSD/Max7456.ino
    - PLATFORMIO_CI_SRC=MW_OSD/Screen.ino
    - PLATFORMIO_CI_SRC=MW_OSDSerial.ino
    - PLATFORMIO_CI_SRC=MW_OSD/SerialMAVLINK.ino
    - PLATFORMIO_CI_SRC=MW_OSD/Config.h
    - PLATFORMIO_CI_SRC=MW_OSD/Def.h
    - PLATFORMIO_CI_SRC=MW_OSD/GlobalVariables.h
    - PLATFORMIO_CI_SRC=MW_OSD/symbols.h

install:
    - pip install -U platformio

script:
    - platformio ci --board=pro16MHzatmega328
 
